services:
  - type: web
    name: dr-harsha-website
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: WA_PHONE_NUMBER_ID
        sync: false
      - key: WA_ACCESS_TOKEN
        sync: false
      - key: DOCTOR_WHATSAPP
        value: "917483749378"
